/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.forms;

import br.edu.ifsul.classes.Tblfuncionario;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author José Henrique
 */
public class Logar extends javax.swing.JFrame {

    /**
     * Creates new form Logar
     */
    public Logar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel1 = new javax.swing.JPanel();
        jLabelcodigofunc = new javax.swing.JLabel();
        jTextFieldcodigofunc = new javax.swing.JTextField();
        jLabelsenhafunc = new javax.swing.JLabel();
        jPasswordfunc = new javax.swing.JPasswordField();
        jButtonlogar = new javax.swing.JButton();
        jButtonlimpar = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setLayout(new java.awt.GridBagLayout());

        jLabelcodigofunc.setText("Código: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        Panel1.add(jLabelcodigofunc, gridBagConstraints);

        jTextFieldcodigofunc.setColumns(10);
        Panel1.add(jTextFieldcodigofunc, new java.awt.GridBagConstraints());

        jLabelsenhafunc.setText("Senha: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        Panel1.add(jLabelsenhafunc, gridBagConstraints);

        jPasswordfunc.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        Panel1.add(jPasswordfunc, gridBagConstraints);

        jButtonlogar.setText("Logar");
        jButtonlogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlogarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        Panel1.add(jButtonlogar, gridBagConstraints);

        jButtonlimpar.setText("Limpar Dados");
        jButtonlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlimparActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        Panel1.add(jButtonlimpar, gridBagConstraints);

        jButtonsair.setText("Sair da Aplicação");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        Panel1.add(jButtonsair, gridBagConstraints);

        getContentPane().add(Panel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlimparActionPerformed
        // TODO add your handling code here:
        if (jPasswordfunc.getPassword().length <= 0 && jTextFieldcodigofunc.getText().length() <= 0) {//caso não contenha dados nos campos
            JOptionPane.showMessageDialog(null, "Não há dados para serem apagados!");
        } else {//caso  haja dados nos campos
            jTextFieldcodigofunc.setText(null);//torna os campos nulos, setando-os.
            jPasswordfunc.setText(null);//-------
        }
    }//GEN-LAST:event_jButtonlimparActionPerformed

    private void jButtonlogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlogarActionPerformed
      if(jTextFieldcodigofunc.getText().length() <= 0 || jPasswordfunc.getText().length() <= 0){
            JOptionPane.showMessageDialog(null, "Insira os dados primeiro!");
        }        
        int codigo = 0;//inicializa uma variavel inteira com zero
        int aux = 0;//inicializa outtra variavel inteira com zero
        try {//condição
            codigo = Integer.parseUnsignedInt(jTextFieldcodigofunc.getText());
            //caso caia na condição pega o codigo digitado na field
        } catch (Exception e) {
            //nao mostra execeção
        }
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProjetoLocatech_TI.2019PU");
        //cria um novo ibj do emf do projeto
        EntityManager em = emf.createEntityManager();
        //cria um nov oobjeto da em, para manipular objetos da tbela
        String jpql = "select f from Tblfuncionario f";
        //string pega a consultada da tabela d banco
        List<Tblfuncionario> listaf = em.createQuery(jpql).getResultList();
        //uma lista da tabela funcionario pega o resultado da query
        for (Tblfuncionario f : listaf) {//para tlbfuncionario == valor da lista
            if (f.getFunCodigo() == codigo && f.getSenha().equalsIgnoreCase(jPasswordfunc.getText())) {
                //se codigo do funcioonaro for igual ao codigo digitado
                //e senha for igual ao jpassowrd func, então libera o acesso
                aux += 1;//variavel auxiliar incrementa mais um
                //chama a trla home
                Home telahome = new Home();//cria um novo objeto do tipo home, que é um frame
                dispose();
                telahome.setVisible(true);//caso exista e esteja visivel, mostra a tela      
            }
        }
        if (aux == 0) {
        JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos, tente novamente!");         
       }      
    }//GEN-LAST:event_jButtonlogarActionPerformed

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        // TODO add your handling code here:
        JFrame framelog = new JFrame();//cria um novo objeto do tipo frame
        framelog.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //o objeto e setado para fechar a operação 
        dispose();
        //fecha a tela anterior
    }//GEN-LAST:event_jButtonsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton jButtonlimpar;
    private javax.swing.JButton jButtonlogar;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JLabel jLabelcodigofunc;
    private javax.swing.JLabel jLabelsenhafunc;
    private javax.swing.JPasswordField jPasswordfunc;
    private javax.swing.JTextField jTextFieldcodigofunc;
    // End of variables declaration//GEN-END:variables
}
