/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.forms;

import javax.swing.JFrame;

/**
 *
 * @author José Henrique
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuferramentas = new javax.swing.JMenu();
        jMenuItemsair = new javax.swing.JMenuItem();
        jMenuservicos = new javax.swing.JMenu();
        jMenuItemcidades = new javax.swing.JMenuItem();
        jMenuItemclientes = new javax.swing.JMenuItem();
        jMenuItemequipamentos = new javax.swing.JMenuItem();
        jMenuItemfunc = new javax.swing.JMenuItem();
        jMenuItemloc = new javax.swing.JMenuItem();
        jMenurelatorios = new javax.swing.JMenu();
        jMenuhelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuferramentas.setText("Ferramentas");

        jMenuItemsair.setText("Sair");
        jMenuItemsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsairActionPerformed(evt);
            }
        });
        jMenuferramentas.add(jMenuItemsair);

        jMenuBar1.add(jMenuferramentas);

        jMenuservicos.setText("Serviços");

        jMenuItemcidades.setText("Cidades");
        jMenuItemcidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemcidadesActionPerformed(evt);
            }
        });
        jMenuservicos.add(jMenuItemcidades);

        jMenuItemclientes.setText("Clientes");
        jMenuservicos.add(jMenuItemclientes);

        jMenuItemequipamentos.setText("Equipamentos");
        jMenuservicos.add(jMenuItemequipamentos);

        jMenuItemfunc.setText("Funcionários");
        jMenuservicos.add(jMenuItemfunc);

        jMenuItemloc.setText("Locação");
        jMenuservicos.add(jMenuItemloc);

        jMenuBar1.add(jMenuservicos);

        jMenurelatorios.setText("Relatórios");
        jMenuBar1.add(jMenurelatorios);

        jMenuhelp.setText("Ajuda");
        jMenuBar1.add(jMenuhelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsairActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemsairActionPerformed

    private void jMenuItemcidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemcidadesActionPerformed
        // TODO add your handling code here:
        JFrame framecidades = new JFrame("Cidades");
        framecidades.setContentPane(new Formcidades());
        framecidades.setExtendedState(JFrame.MAXIMIZED_BOTH);
        framecidades.pack();
        framecidades.setLocationRelativeTo(null);
        framecidades.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemcidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemcidades;
    private javax.swing.JMenuItem jMenuItemclientes;
    private javax.swing.JMenuItem jMenuItemequipamentos;
    private javax.swing.JMenuItem jMenuItemfunc;
    private javax.swing.JMenuItem jMenuItemloc;
    private javax.swing.JMenuItem jMenuItemsair;
    private javax.swing.JMenu jMenuferramentas;
    private javax.swing.JMenu jMenuhelp;
    private javax.swing.JMenu jMenurelatorios;
    private javax.swing.JMenu jMenuservicos;
    // End of variables declaration//GEN-END:variables
}
